### ISSUE TITLE
Step 2 fails

### ISSUE THREAD

**Issue by nzzoli3** [esimonetti/SugarActivityStreamPurger#1]
Hello. I try to use your code. I did the composer install step, but when I try to do:
./vendor/bin/package 1.2
it says something about missing class ZipArchieve.
Proof:
********@*******:/var/www/*******/activitypurge# ./vendor/bin/package 1.2
Creating releases/module_activitystreampurger_1.2.zip...
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /var/www/*****/activitypurge/vendor/esimonetti/sugar-module-packager/src/PackageUtils.php:237
Stack trace:
#0 /var/www/*******/activitypurge/vendor/esimonetti/sugar-module-packager/src/PackageUtils.php(287): SugarModulePackager\PackageUtils::generateZipPackage()
#1 /var/www/*******/activitypurge/vendor/esimonetti/sugar-module-packager/bin/package(21): SugarModulePackager\PackageUtils::build()
#2 {main}
  thrown in /var/www/********/activitypurge/vendor/esimonetti/sugar-module-packager/src/PackageUtils.php on line 237

**Comment by esimonetti** [comment]
Hi there,

You are missing ZipArchive (see something like this https://stackoverflow.com/questions/3872555/fatal-error-class-ziparchive-not-found-in)

```
~/aaa/SugarActivityStreamPurger$ ./vendor/bin/package 1.2
Creating releases/module_activitystreampurger_1.2.zip...
* Skipped manifest copy directive for LICENSE
* Skipped manifest copy directive for scripts/post_execute.php
* Skipped manifest copy directive for scripts/post_uninstall.php
* Skipped manifest copy directive for README.txt
* Automatically added manifest copy directive for custom/Extension/application/Ext/Console/ActivityStreamCleanup.php
* Automatically added manifest copy directive for custom/Extension/modules/Schedulers/Ext/Language/en_us.activitystreampurger.php
* Automatically added manifest copy directive for custom/Extension/modules/Schedulers/Ext/ScheduledTasks/ActivityStreamPurgerJob.php
* Automatically added manifest copy directive for custom/src/activitystream/ActivityStreamCleaner.php
* Automatically added manifest copy directive for custom/src/Console/Command/ActivityStreamCleanup/ActivityStreamCleanupCommand.php
SugarModulePackager v0.2.2 successfully packaged releases/module_activitystreampurger_1.2.zip
```

As this is packaged with sugar module packager (read more here: https://packagist.org/packages/esimonetti/sugar-module-packager) the alternative, if you have docker, is to use _package-docker_ instead:

```
~/aaa/SugarActivityStreamPurger$ ./vendor/bin/package-docker 1.2
Creating releases/module_activitystreampurger_1.2.zip...
* Skipped manifest copy directive for LICENSE
* Skipped manifest copy directive for scripts/post_execute.php
* Skipped manifest copy directive for scripts/post_uninstall.php
* Skipped manifest copy directive for README.txt
* Automatically added manifest copy directive for custom/Extension/application/Ext/Console/ActivityStreamCleanup.php
* Automatically added manifest copy directive for custom/Extension/modules/Schedulers/Ext/Language/en_us.activitystreampurger.php
* Automatically added manifest copy directive for custom/Extension/modules/Schedulers/Ext/ScheduledTasks/ActivityStreamPurgerJob.php
* Automatically added manifest copy directive for custom/src/activitystream/ActivityStreamCleaner.php
* Automatically added manifest copy directive for custom/src/Console/Command/ActivityStreamCleanup/ActivityStreamCleanupCommand.php
SugarModulePackager v0.2.2 successfully packaged releases/module_activitystreampurger_1.2.zip
```

Hope it helps
